tap "thoughtbot/formulae"
brew "rcm"
brew "fzf"
brew "grep"
cask "1password"
brew "universal-ctags/universal-ctags/universal-ctags", args: ['HEAD']
cask "1password-cli"
cask "amethyst"
brew "neovim"
cask "skitch"
brew "liquidprompt"
