#!/usr/bin/env bash
defaults write -g NSRequiresAquaSystemAppearance -bool false
defaults write -g AppleInterfaceStyleSwitchesAutomatically -bool FALSE
defaults write -g "AppleInterfaceStyle" "Dark"
defaults write -g AppleICUForce24HourTime -bool true 

defaults write com.apple.Dock autohide-delay -float 0

defaults write com.apple.dock tilesize -int 16
defaults write com.apple.dock magnification -bool false
defaults write com.apple.dock size-immutable -bool true
defaults write com.apple.dock 'orientation' -string 'left'
defaults write com.apple.Dock autohide -bool true
killall Dock
defaults write com.apple.menuextra.battery ShowPercent -bool yes

defaults write com.apple.menuextra.clock DateFormat -string 'M d  H:mm'
killall SystemUIServer
defaults write com.apple.spotlight DictionaryLookupEnabled NO
killall Spotlight
defaults -currentHost write "com.apple.screensaver" showClock -bool true
defaults -currentHost write "com.apple.screensaver" moduleDict -dict moduleName "Word of the Day" path "/System/Library/Screen Savers/Word of the Day.saver"  type 0
